import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import Hero from '@/components/Hero';
import About from '@/components/About';
import DepositCard from '@/components/DepositCard';
import Services from '@/components/Services';
import Banner from '@/components/Banner';
import LoanCard from '@/components/LoanCard';
import ContactForm from '@/components/ContactForm';
import AuthContext from '@/components/AuthContext';
import { useContext } from 'react';
import Verify from '@/components/dashboard/Verify';

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	const { user }: any = useContext(AuthContext);

	return (
		<>
			<Head>
				<title>somerset Credit Union Bank</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				{/* <h1>{user?.email}</h1> */}
				<Hero />
				{/* <Verify /> */}
				<About />
				<DepositCard />
				<LoanCard />
				<Banner />
				<Services />
				<ContactForm />
				<h1>We served over 500+ Customers</h1>
				<div className='line'></div>
			</main>
		</>
	);
}
