import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '../styles/Dashboard.module.css';
import Hero from '@/components/Hero';
import About from '@/components/About';
import DepositCard from '@/components/DepositCard';
import Services from '@/components/Services';
import Banner from '@/components/Banner';
import LoanCard from '@/components/LoanCard';
import ContactForm from '@/components/ContactForm';
import AuthContext from '@/components/AuthContext';
import { useContext, useState } from 'react';
import Verify from '@/components/dashboard/Verify';
import Spinner from '@/components/Spinner';

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	const { user }: any = useContext(AuthContext);
	const [edit, setEdit] = useState(false);

	return (
		<>
			<Head>
				<title>somerset Credit Union Bank</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<Hero />
				<About />
				<DepositCard />
				<LoanCard />
				<Banner />
				<Services />
				<ContactForm />
				<h1>We served over 500+ Customers</h1>
				<div className='line'></div>
			</main>
		</>
	);
}
